const EKEY='labsains_equipment', CKEY='labsains_chemicals';
const demoE=[{name:'Mikroskop',code:'MIC-023',location:'Kabinet A2',status:'Baik'},{name:'Bikar 100ml',code:'BK-100',location:'Rak B1',status:'Baik'},{name:'Tabung Uji',code:'TU-001',location:'Rak B2',status:'Rosak'}];
const demoC=[{name:'Hydrochloric Acid',formula:'HCl',qty:2.5,unit:'L',expiry:'2027-12-01',hazard:'Mengakis',location:'Kabinet Kimia A'},{name:'Sodium Hydroxide',formula:'NaOH',qty:0.5,unit:'kg',expiry:'2027-08-01',hazard:'Mengakis',location:'Kabinet Kimia A'}];
let equipment=JSON.parse(localStorage.getItem(EKEY)||'null')||demoE, chemicals=JSON.parse(localStorage.getItem(CKEY)||'null')||demoC;
function save(){localStorage.setItem(EKEY,JSON.stringify(equipment));localStorage.setItem(CKEY,JSON.stringify(chemicals));updateStats()}
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');renderEquipment();renderChemicals()}
function updateStats(){equipmentCount.textContent=equipment.length;chemicalCount.textContent=chemicals.length;alertCount.textContent=equipment.filter(x=>x.status!='Baik').length+chemicals.filter(x=>x.qty<=1).length}
function renderEquipment(){let q=(eqSearch.value||'').toLowerCase();equipmentList.innerHTML=equipment.filter(x=>(x.name+x.code+x.location).toLowerCase().includes(q)).map((x,i)=>`<div class="item"><b>${x.name}</b><small>${x.code} • ${x.location}</small><span class="badge ${x.status=='Rosak'?'warn':x.status=='Hilang'?'danger':''}">${x.status}</span><div style="margin-top:10px"><button onclick="editEquipment(${i})">Edit</button> <button onclick="deleteEquipment(${i})">Padam</button></div></div>`).join('')||'<p>Tiada rekod.</p>'}
function renderChemicals(){let q=(chemSearch.value||'').toLowerCase();chemicalList.innerHTML=chemicals.filter(x=>(x.name+x.formula+x.location).toLowerCase().includes(q)).map((x,i)=>{let low=x.qty<=1;return `<div class="item"><b>${x.name}</b><small>${x.formula} • ${x.qty} ${x.unit} • ${x.location}</small><small>Luput: ${x.expiry} • Bahaya: ${x.hazard}</small><span class="badge ${low?'warn':''}">${low?'⚠️ Stok Rendah':'Stok OK'}</span><div style="margin-top:10px"><button onclick="editChemical(${i})">Edit</button> <button onclick="deleteChemical(${i})">Padam</button></div></div>`}).join('')||'<p>Tiada rekod.</p>'}
function openEquipmentForm(i=null){modalTitle.textContent=i===null?'Tambah Peralatan':'Edit Peralatan';let x=i===null?{name:'',code:'',location:'',status:'Baik'}:equipment[i];modalBody.innerHTML=`<input id="f1" placeholder="Nama" value="${x.name}"><input id="f2" placeholder="Kod" value="${x.code}"><input id="f3" placeholder="Lokasi" value="${x.location}"><select id="f4"><option>Baik</option><option>Rosak</option><option>Hilang</option></select><button onclick="saveEquipment(${i})">Simpan</button>`;f4.value=x.status;modal.style.display='block'}
function saveEquipment(i){let x={name:f1.value,code:f2.value,location:f3.value,status:f4.value};if(!x.name)return;if(i===null)equipment.push(x);else equipment[i]=x;save();closeModal();renderEquipment()}
function editEquipment(i){openEquipmentForm(i)} function deleteEquipment(i){if(confirm('Padam rekod ini?')){equipment.splice(i,1);save();renderEquipment()}}
function openChemicalForm(i=null){modalTitle.textContent=i===null?'Tambah Bahan Kimia':'Edit Bahan Kimia';let x=i===null?{name:'',formula:'',qty:'',unit:'L',expiry:'',hazard:'',location:''}:chemicals[i];modalBody.innerHTML=`<input id="c1" placeholder="Nama bahan" value="${x.name}"><input id="c2" placeholder="Formula" value="${x.formula}"><div class="row"><input id="c3" type="number" step="0.01" placeholder="Kuantiti" value="${x.qty}"><input id="c4" placeholder="Unit" value="${x.unit}"></div><input id="c5" type="date" value="${x.expiry}"><input id="c6" placeholder="Tahap bahaya" value="${x.hazard}"><input id="c7" placeholder="Lokasi" value="${x.location}"><button onclick="saveChemical(${i})">Simpan</button>`;modal.style.display='block'}
function saveChemical(i){let x={name:c1.value,formula:c2.value,qty:Number(c3.value),unit:c4.value,expiry:c5.value,hazard:c6.value,location:c7.value};if(!x.name)return;if(i===null)chemicals.push(x);else chemicals[i]=x;save();closeModal();renderChemicals()}
function editChemical(i){openChemicalForm(i)} function deleteChemical(i){if(confirm('Padam bahan ini?')){chemicals.splice(i,1);save();renderChemicals()}} function closeModal(){modal.style.display='none'}
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.hidden=false});installBtn.onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');save();renderEquipment();renderChemicals();
